apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-ordens-servico-config
  namespace: oficina
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Database__ApplyMigrations: "false"
  DistributedFlow__Enabled: "true"
  PAYMENTS_USE_MOCK: "true"
  Payments__UseMock: "true"
  Payments__Mode: "Mock"
  Payments__TimeoutSeconds: "5"
  Integrations__Cadastro__BaseUrl: "__CADASTRO_BASE_URL__"
  Integrations__Estoque__BaseUrl: "__ESTOQUE_BASE_URL__"
  Messaging__Sqs__Enabled: "true"
  Messaging__Sqs__Region: "__AWS_REGION__"
  Messaging__Sqs__CommandsQueueUrl: "__COMMANDS_QUEUE_URL__"
  Messaging__Sqs__CommandsDlqQueueUrl: "__COMMANDS_DLQ_URL__"
  Messaging__Sqs__EventsQueueUrl: "__EVENTS_QUEUE_URL__"
  Messaging__Sqs__EventsDlqQueueUrl: "__EVENTS_DLQ_URL__"
  Messaging__Sqs__ConsumerConcurrency: "1"
  Messaging__Sqs__MaxMessagesPerReceive: "1"
  Messaging__Sqs__WaitTimeSeconds: "20"
  Messaging__Sqs__VisibilityTimeoutSeconds: "60"
  Authentication__Mode: ""
